### ISSUE TITLE
Posso melhorar e adicionar outros recursos nessa página?

### ISSUE THREAD

**Issue by ghost** [abelsiqueira/abelsiqueira.github.io-old#1]
Posso melhorar e adicionar outros recursos nessa página?

**Comment by ghost** [comment]
Gostaria de fazer isso por você! Essa é uma ideia inicial e pode sofrer alterações, mas é um começo rs...
![novo](https://user-images.githubusercontent.com/46846354/56476229-3aa9de00-646b-11e9-8e85-9a6b625b4a66.png)

**Comment by abelsiqueira** [comment]
Olá @pedroguilhermelima, não é necessário, eu gosto de controlar a minha página eu mesmo, mas se tiver algo errado, agradeço se avisar.
Por que o interesse?

**Comment by ghost** [comment]
Existe algo errado... Rs em oferecer um novo Web Design? 

Rs.. Eu gostei da proposta do Github e posso ajudar todo mundo com apenas um click e uma conexão com a internet. Por exemplo, posso olhar as diferentes resoluções para um problema e em várias perspectivas colaborar ou esperar grandes mudanças por uma ou mais ações minhas como "pull request/commit/fork..." para o software ou hardware.   

E existem outras opções que são válidas como a documentação, a tradução, ajudar com conceitos e ideias ou mesmo o Web Design nessa questão de "pull request/commit/fork".

Vi em seu repositório uma maneira de ajudar e colaborar. Caso queira, ótimo. Caso não, tudo bem.  Sou uma pessoa que procura soluções e não problemas.  **;D**  Por definição de qualidade, apresentação hoje em termos como "acesso a páginas via mobile,  responsividade" achei que seria interessante,  de enorme ajuda e colaboração também. 

Atenciosamente,
Pedro Guilherme.

**Comment by pedroguilhermelima** [comment]
E existem outras opções que são válidas como a documentação, a tradução, ajudar com conceitos e ideias ou mesmo o Web Design nessa questão de "pull request/commit/fork".

**Comment by abelsiqueira** [comment]
@pedroguilhermelima, eu dei uma olhada na sua estratégia de entrada no GitHub e, na minha opinião, ela está errada. Você está entrando em algumas páginas aleatórias e tentando fazer alguma coisa, possivelmente para montar porfolio e ter atividade na rede. Tem alguns problemas na sua abordagem:

1- Eu não te conheço, assim como várias pessoas que você começa o contato não te conhecem. Numa página pessoal, como a minha, não faz sentido você chegar com uma proposta de mudança de layout.

2- Em projetos existentes, (ex: bootstrap), é preciso conhecer a proposta do projeto pra saber se suas modificações fazem sentido. Submissão de código sem motivo não é uma contribuição válida. Quando você cria issues e pull requests num repositório alheio, alguém precisa dedicar um tempo da vida pra avaliar o que você está fazendo, e se não estiver claro gasta-se um tempo ainda maior pra tentar entender.

3- Se você quer ajudar, - e montar portfolio no processo - existem lugares adequados. No caso de Web Design, veja o https://www.freecodecamp.org/.

Parabéns pela iniciativa, mas recomendo entender melhor a dinâmica do GitHub e colaboração online.

**Comment by ghost** [comment]
Okay... como eu disse eu ajudo como posso... Rs, eu não preciso de ninguém... rs. Eu aprendo sozinho e sobre o Bootstrap eu nem uso kkkk E sobre portfólio a única coisa que mostro são os resultados.  Outra coisa " que estratégia"? Eu não tive nenhuma... eu faço as coisas para melhorar e se eles não querem ou você não quer... tudo bem. Eu só vou mostrar como vocês poderiam... ser e como eu ajudei nesse processo. Tipo... eu mostro as coisas antes e depois... Outra coisa... eu sou rs... Web Designer, porém amo artes e programação... então quando faço algo é com sentido... Eu falei com o Bootstrap por achar que seria interessante, mas parecem que são fechados... é a mesma coisa de mostrar para um ignorante seu erro... Rs, não vale a pena... a pessoa não aceita... e isso não é comigo é com ela... Se estou errado não justifico um erro por outro. Valeu pelas suas considerações... ajudar... você ajuda quem pode até desconhecidos ou conhecidos... seria a mesma coisa da pessoa ser honesta de faixada kkkk só para impressionar quando não é. 


Eu fiz as issues e vou terminar o que comecei. Se quiser bem e se não okay. Eu só faço o meu trabalho... que é embora não saibam... de melhorar sistemas. Eu amo isso e vou morrer com isso. Farei o PHP.js, ReviewReact, Expressões Cômicas ( Gramática para o ReviewReact), Check, Niev ( Meu Browser ).... rs E vou incluir meu WebDesign aí kkkk Fork não custa nada e acredito que seria bom assim.

**Comment by pedroguilhermelima** [comment]
Notas de rodapé: Todos os softwares mudam e pessoas também. Será que Windows antigo e o atual são iguais? Oh... claro que não. Será que o Linux antigo e atual são iguais? Oh... claro que não. Será que o Bootstrap é o mesmo? Existem várias versões... Eu farei a minha ;D Reparei que você usa a linguagem Júlia. Eu já programei nela kkkk Eu vou ver como ajudar nesse sentido.
